name: 提醒动画更新

on:
  workflow_dispatch:
  schedule:
    - cron: "0/30 0-16 * * *"

env:
  GIT_USER: Gadfly
  GIT_EMAIL: gadfly@gadfly.vip
  TZ: Asia/Shanghai

jobs:
  notify-anime-update:
    name: 提醒动画更新 on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22.x]

    steps:
      - name: Setup Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_PRI }}
          known_hosts: 'github.com'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: |
          yarn

      - name: execute script
        run: |
          yarn notify-anime -mailUser="${{ secrets.MAIL_USER }}" -mailPass="${{ secrets.MAIL_PASS }}" -mailFrom="${{ secrets.MAIL_FROM }}" -mailTo="${{ secrets.MAIL_TO }}"

      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: submit updated files
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git add -A
          git commit -m "update anime"
          git push
